export interface LocationHierarchy {
  [state: string]: {
    [district: string]: string[];
  };
}

export const INDIAN_LOCATION_DATA: LocationHierarchy = {
  "Andhra Pradesh": {
    "Visakhapatnam": ["Visakhapatnam", "Gajuwaka", "Anakapalle", "Bheemunipatnam", "Pendurthi", "Madhurawada"],
    "Krishna": ["Vijayawada", "Machilipatnam", "Gudivada", "Nuzvid", "Jaggayyapeta", "Vuyyuru"],
    "Guntur": ["Guntur", "Tenali", "Narasaraopet", "Mangalagiri", "Bapatla", "Sattenapalle", "Ponnur"],
    "Chittoor": ["Tirupati", "Chittoor", "Madanapalle", "Srikalahasti", "Punganur", "Nagari", "Pileru"],
    "East Godavari": ["Kakinada", "Rajahmundry", "Amalapuram", "Samalkot", "Mandapeta", "Peddapuram", "Pithapuram"],
    "West Godavari": ["Eluru", "Bhimavaram", "Tadepalligudem", "Tanuku", "Palakollu", "Narsapur", "Jangareddygudem"],
    "Kurnool": ["Kurnool", "Nandyal", "Adoni", "Yemmiganur", "Dhone", "Allagadda", "Nandikotkur"],
    "Anantapur": ["Anantapur", "Hindupur", "Dharmavaram", "Guntakal", "Kadiri", "Tadipatri", "Rayadurg"],
    "Nellore": ["Nellore", "Kavali", "Gudur", "Venkatagiri", "Atmakur", "Sullurpeta", "Naidupeta"],
    "Kadapa (YSR)": ["Kadapa", "Proddatur", "Pulivendula", "Jammalamadugu", "Rayachoti", "Rajampet", "Badvel"],
    "Srikakulam": ["Srikakulam", "Amadalavalasa", "Palasa-Kasibugga", "Ichchapuram", "Rajam"],
    "Vizianagaram": ["Vizianagaram", "Bobbili", "Parvathipuram", "Salur", "Cheepurupalli"],
    "Prakasam": ["Ongole", "Chirala", "Kandukur", "Markapur", "Giddalur", "Podili"],
  },
  "Telangana": {
    "Hyderabad": ["Hyderabad", "Secunderabad", "Ameerpet", "Banjara Hills", "Jubilee Hills", "Charminar", "Gachibowli", "Hitec City", "Madhapur", "Kondapur", "Kukatpally", "Dilsukhnagar", "LB Nagar", "Begumpet", "Somajiguda"],
    "Rangareddy": ["Shamshabad", "Manikonda", "Rajendranagar", "Ibrahimpatnam", "Shadnagar", "Chevella", "Moinabad"],
    "Medchal-Malkajgiri": ["Kukatpally", "Medchal", "Malkajgiri", "Alwal", "Quthbullapur", "Kompally", "Bowenpally"],
    "Warangal": ["Warangal", "Hanamkonda", "Kazipet", "Narsampet", "Parkal", "Wardhannapet"],
    "Karimnagar": ["Karimnagar", "Huzurabad", "Jammikunta", "Choppadandi", "Manakondur"],
    "Nizamabad": ["Nizamabad", "Armoor", "Bodhan", "Bheemgal", "Kamareddy"],
    "Khammam": ["Khammam", "Kothagudem", "Madhira", "Sathupalli", "Yellandu", "Bhadrachalam"],
    "Nalgonda": ["Nalgonda", "Miryalaguda", "Suryapet", "Devarakonda", "Bhongir", "Kodad"],
    "Sangareddy": ["Sangareddy", "Patancheru", "Zaheerabad", "Ameenpur", "Sadasivpet", "Narsapur"],
    "Mahbubnagar": ["Mahbubnagar", "Jadcherla", "Nagarkurnool", "Wanaparthy", "Gadwal", "Narayanpet"],
    "Peddapalli": ["Ramagundam", "Peddapalli", "Godavarikhani", "Manthani", "Sultanabad"],
    "Siddipet": ["Siddipet", "Gajwel", "Dubbak", "Husnabad"],
    "Jagtial": ["Jagtial", "Korutla", "Metpally", "Raikal"],
    "Adilabad": ["Adilabad", "Mancherial", "Nirmal", "Bellampalli", "Mandamarri", "Asifabad"],
  },
  "Karnataka": {
    "Bengaluru Urban": ["Bangalore", "Whitefield", "Electronic City", "Koramangala", "Indiranagar", "Jayanagar", "JP Nagar", "HSR Layout", "Marathahalli", "Yelahanka", "Hebbal", "Malleshwaram", "Rajajinagar", "BTM Layout"],
    "Bengaluru Rural": ["Doddaballapura", "Devanahalli", "Hosakote", "Nelamangala"],
    "Mysuru": ["Mysore", "Nanjangud", "Hunsur", "T. Narasipura", "K.R. Nagar", "Piriyapatna"],
    "Dakshina Kannada": ["Mangalore", "Bantwal", "Puttur", "Belthangady", "Sullia", "Moodbidri"],
    "Belagavi": ["Belgaum", "Gokak", "Chikkodi", "Athani", "Bailhongal", "Savadatti"],
    "Dharwad": ["Hubli", "Dharwad", "Kundgol", "Navalgund", "Kalghatgi"],
    "Kalaburagi": ["Gulbarga", "Sedam", "Shahabad", "Wadi", "Aland", "Chincholi"],
    "Udupi": ["Udupi", "Manipal", "Kundapura", "Karkala", "Kaup", "Byndoor"],
    "Shivamogga": ["Shimoga", "Bhadravati", "Sagar", "Shikaripura", "Thirthahalli"],
    "Tumakuru": ["Tumkur", "Tiptur", "Sira", "Kunigal", "Madhugiri"],
    "Ballari": ["Bellary", "Hospet", "Sandur", "Siruguppa", "Kudligi"],
  },
  "Maharashtra": {
    "Mumbai City": ["Mumbai", "Colaba", "Fort", "Dadar", "Marine Lines", "Worli", "Byculla", "Lower Parel"],
    "Mumbai Suburban": ["Andheri", "Bandra", "Borivali", "Juhu", "Goregaon", "Malad", "Kandivali", "Powai", "Ghatkopar", "Kurla", "Mulund", "Chembur"],
    "Thane": ["Thane", "Navi Mumbai", "Kalyan", "Dombivli", "Mira-Bhayandar", "Ulhasnagar", "Bhiwandi", "Badlapur", "Ambernath"],
    "Pune": ["Pune", "Pimpri-Chinchwad", "Hinjewadi", "Hadapsar", "Kothrud", "Baner", "Viman Nagar", "Wakad", "Aundh", "Shivajinagar", "Kharadi", "Magarpatta"],
    "Nagpur": ["Nagpur", "Kamptee", "Umred", "Katol", "Ramtek", "Hingna"],
    "Nashik": ["Nashik", "Malegaon", "Sinnar", "Manmad", "Deolali", "Igatpuri"],
    "Chhatrapati Sambhajinagar": ["Aurangabad", "Jalna", "Paithan", "Vaijapur", "Gangapur", "Kannad"],
    "Kolhapur": ["Kolhapur", "Ichalkaranji", "Jaysingpur", "Kagal", "Gadhinglaj"],
    "Solapur": ["Solapur", "Pandharpur", "Barshi", "Akkalkot", "Sangola"],
  },
  "Tamil Nadu": {
    "Chennai": ["Chennai", "Anna Nagar", "T. Nagar", "Velachery", "Adyar", "Mylapore", "Tambaram", "Guindy", "Chromepet", "Porur", "Thiruvanmiyur"],
    "Coimbatore": ["Coimbatore", "Pollachi", "Mettupalayam", "Sulur", "Valparai", "Annur"],
    "Madurai": ["Madurai", "Tirumangalam", "Melur", "Usilampatti", "Vadipatti", "Sholavandan"],
    "Tiruchirappalli": ["Trichy", "Srirangam", "Manapparai", "Thiruverumbur", "Musiri", "Lalgudi"],
    "Salem": ["Salem", "Attur", "Mettur", "Edappadi", "Omalur", "Sankagiri"],
    "Chengalpattu": ["Chengalpattu", "Tambaram", "Pallavaram", "Maraimalai Nagar", "Mahabalipuram", "Vandalur"],
    "Kanchipuram": ["Kanchipuram", "Sriperumbudur", "Kundrathur", "Uthiramerur", "Walajabad"],
    "Tirunelveli": ["Tirunelveli", "Palayamkottai", "Ambasamudram", "Nanguneri", "Radhapuram"],
    "Vellore": ["Vellore", "Katpadi", "Gudiyatham", "Anaicut", "K.V. Kuppam"],
    "Erode": ["Erode", "Gobichettipalayam", "Bhavani", "Perundurai", "Sathyamangalam"],
  },
  "Delhi": {
    "New Delhi": ["New Delhi", "Connaught Place", "Chanakyapuri", "Vasant Kunj", "Lutyens Delhi", "Barakhamba"],
    "South Delhi": ["Saket", "Hauz Khas", "Greater Kailash", "South Extension", "Green Park", "Malviya Nagar", "Mehrauli", "Alaknanda"],
    "South East Delhi": ["Lajpat Nagar", "Defence Colony", "Nehru Place", "Kalkaji", "Sarita Vihar", "Okhla", "Jasola"],
    "Central Delhi": ["Karol Bagh", "Pahar Ganj", "Rajendra Nagar", "Daryaganj", "Pusa Road"],
    "West Delhi": ["Janakpuri", "Rajouri Garden", "Punjabi Bagh", "Tilak Nagar", "Paschim Vihar", "Patel Nagar", "Uttam Nagar"],
    "North Delhi": ["Civil Lines", "Model Town", "Kamla Nagar", "Sadar Bazar", "Shakti Nagar"],
    "North West Delhi": ["Rohini", "Pitampura", "Shalimar Bagh", "Prashant Vihar", "Ashok Vihar", "Kanjhawala"],
    "East Delhi": ["Laxmi Nagar", "Preet Vihar", "Mayur Vihar", "Patparganj", "Geeta Colony", "Shakarpur"],
    "South West Delhi": ["Dwarka", "Vasant Vihar", "Najafgarh", "Palam", "Janakpuri South", "Mahipalpur"],
  },
  "Kerala": {
    "Ernakulam": ["Kochi", "Ernakulam", "Aluva", "Kakkanad", "Angamaly", "Perumbavoor", "Tripunithura", "Muvattupuzha", "Kothamangalam"],
    "Thiruvananthapuram": ["Trivandrum", "Neyyattinkara", "Attingal", "Nedumangad", "Varkala", "Kazhakkoottam", "Kovalam"],
    "Kozhikode": ["Calicut", "Kozhikode", "Vadakara", "Koyilandy", "Feroke", "Ramanattukara"],
    "Thrissur": ["Thrissur", "Guruvayur", "Chalakudy", "Kodungallur", "Kunnamkulam", "Irinjalakuda"],
    "Kottayam": ["Kottayam", "Changanassery", "Pala", "Kanjirappally", "Vaikom", "Ettumanoor"],
    "Palakkad": ["Palakkad", "Ottapalam", "Chittur-Thathamangalam", "Shornur", "Mannarkkad"],
  },
  "Gujarat": {
    "Ahmedabad": ["Ahmedabad", "Bopal", "Satellite", "Navrangpura", "SG Highway", "Maninagar", "Prahlad Nagar", "Bodakdev", "Chandkheda"],
    "Surat": ["Surat", "Adajan", "Vesu", "Varachha", "Piplod", "Katargam", "Rander", "Udhna"],
    "Vadodara": ["Vadodara", "Alkapuri", "Gotri", "Manjalpur", "Akota", "Fatehgunj", "Karelibaug"],
    "Rajkot": ["Rajkot", "Kalawad Road", "University Road", "Yagnik Road", "Morbi", "Gondal"],
    "Gandhinagar": ["Gandhinagar", "Infocity", "Kudasan", "Sector 21", "Mansha", "Kalol"],
  },
  "West Bengal": {
    "Kolkata": ["Kolkata", "Park Street", "Ballygunge", "Alipore", "Salt Lake", "New Town", "Rajarhat", "Tollygunge", "Behala", "Garia", "Dum Dum"],
    "North 24 Parganas": ["Barasat", "Barrackpore", "Bidhannagar", "Habra", "Kalyani", "Naihati"],
    "Howrah": ["Howrah", "Bally", "Uluberia", "Santragachi", "Shibpur"],
    "Darjeeling": ["Siliguri", "Darjeeling", "Kurseong", "Mirik"],
  },
  "Punjab": {
    "Ludhiana": ["Ludhiana", "Khanna", "Jagraon", "Samrala", "Doraha"],
    "Amritsar": ["Amritsar", "Majitha", "Ajnala", "Attari", "Jandiala Guru"],
    "Jalandhar": ["Jalandhar", "Phagwara", "Nakodar", "Shahkot", "Kartarpur"],
    "SAS Nagar (Mohali)": ["Mohali", "Kharar", "Zirakpur", "Dera Bassi", "Kurali"],
    "Patiala": ["Patiala", "Nabha", "Rajpura", "Samana"],
  },
  "Rajasthan": {
    "Jaipur": ["Jaipur", "Mansarovar", "Malviya Nagar", "Vaishali Nagar", "C-Scheme", "Jagatpura", "Tonk Road"],
    "Jodhpur": ["Jodhpur", "Shastri Nagar", "Ratanada", "Pal Road", "Sardarpura"],
    "Udaipur": ["Udaipur", "Hiran Magri", "Fatehpura", "Sukher", "Bhuwana"],
  },
  "Uttar Pradesh": {
    "Gautam Buddha Nagar (Noida)": ["Noida", "Greater Noida", "Noida Extension", "Sector 62", "Sector 18", "Sector 137"],
    "Ghaziabad": ["Ghaziabad", "Indirapuram", "Vaishali", "Vasundhara", "Raj Nagar Extension", "Crossings Republik"],
    "Lucknow": ["Lucknow", "Gomti Nagar", "Aliganj", "Hazratganj", "Indira Nagar", "Mahanagar", "Jankipuram"],
    "Kanpur": ["Kanpur", "Civil Lines", "Kakadeo", "Kalyanpur", "Swaroop Nagar"],
    "Varanasi": ["Varanasi", "Lanka", "Sigra", "Cantt", "Bhelupur"],
  },
};
