export const EDUCATION_OPTIONS = [
  "10th",
  "Higher Secondary / 12th",
  "Diploma / Polytechnic",
  "Bachelor's - Engineering / Computer Science",
  "Master's - Engineering / Computer Science",
  "Bachelor's - Arts / Science / Commerce",
  "Master's - Arts / Science / Commerce",
  "Bachelor's - Management",
  "Master's - Management",
  "Bachelor's - Medicine - General / Dental / Surgeon",
  "Master's - Medicine - General / Dental / Surgeon",
  "Bachelor's - Pharmacy / Nursing or Health Sciences",
  "Master's - Pharmacy / Nursing or Health Sciences",
  "Bachelor's - Legal",
  "Master's - Legal",
  "Finance - ICWAI / CA / CS / CFA",
  "Civil Services",
  "Doctorates",
  "Others",
];

export const MARITAL_STATUS_OPTIONS = [
  "Never Married",
  "Divorced",
  "Widowed",
  "Awaiting Divorce",
  "Annulled",
];

export const SMOKING_OPTIONS = ["No", "Yes", "Occasionally"];

export const DRINKING_OPTIONS = ["No", "Yes", "Socially"];

export const DIET_OPTIONS = [
  "Vegetarian",
  "Non-Vegetarian",
  "Eggetarian",
  "Vegan",
  "Jain",
];

export const OCCUPATION_OPTIONS = [
  "Any",
  "Administration",
  "Agriculture",
  "Airline",
  "Architecture & Design",
  "Banking & Finance",
  "Beauty & Fashion",
  "BPO & Customer Service",
  "Civil Services",
  "Corporate Professionals",
  "Defence",
  "Doctor",
  "Education & Training",
  "Engineering",
  "Hospitality",
  "IT & Software",
  "Legal",
  "Media & Entertainment",
  "Medical & Healthcare - Others",
  "Merchant Navy",
  "Police / Law Enforcement",
  "Scientist",
  "Senior Management",
  "Others",
];

export const INCOME_CURRENCIES = ["INR (₹)", "USD ($)", "GBP (£)", "EUR (€)", "AED (د.إ)", "AUD ($)"];

export const INCOME_AMOUNTS = [
  "Below 50K",
  "50K",
  "1–2 Lakhs",
  "2–3 Lakhs",
  "3–5 Lakhs",
  "5–10 Lakhs",
  "10–15 Lakhs",
  "15–20 Lakhs",
  "20–30 Lakhs",
  "30–50 Lakhs",
  "50 Lakhs–1 Crore",
  "1 Crore and Above",
];

export const GOTHRAM_OPTIONS = [
  "Kasyapa",
  "Bharadwaja",
  "Vasishta",
  "Vishwamitra",
  "Gautama",
  "Atri",
  "Agastya",
  "Kaushika",
  "Jamadagni",
  "Harita",
  "Koundinya",
  "Shandilya",
  "Others",
];

export const RASHI_OPTIONS = [
  "Mesha (Aries)",
  "Vrishabha (Taurus)",
  "Mithuna (Gemini)",
  "Karka (Cancer)",
  "Simha (Leo)",
  "Kanya (Virgo)",
  "Tula (Libra)",
  "Vrischika (Scorpio)",
  "Dhanu (Sagittarius)",
  "Makara (Capricorn)",
  "Kumbha (Aquarius)",
  "Meena (Pisces)",
];

export const NAKSHATRA_OPTIONS = [
  "Ashwini",
  "Bharani",
  "Krittika",
  "Rohini",
  "Mrigashira",
  "Ardra",
  "Punarvasu",
  "Pushya",
  "Ashlesha",
  "Magha",
  "Purva Phalguni",
  "Uttara Phalguni",
  "Hasta",
  "Chitra",
  "Swati",
  "Vishakha",
  "Anuradha",
  "Jyeshtha",
  "Mula",
  "Purva Ashadha",
  "Uttara Ashadha",
  "Shravana",
  "Dhanishta",
  "Shatabhisha",
  "Purva Bhadrapada",
  "Uttara Bhadrapada",
  "Revati",
];

export const MOTHER_TONGUE_OPTIONS = [
  "Telugu",
  "Hindi",
  "English",
  "Tamil",
  "Kannada",
  "Malayalam",
  "Marathi",
  "Bengali",
  "Gujarati",
  "Punjabi",
  "Urdu",
  "Odia",
  "Assamese",
  "Konkani",
  "Sanskrit",
  "Others",
];

export const FAMILY_VALUE_OPTIONS = ["Orthodox", "Traditional", "Moderate", "Liberal"];
export const FAMILY_TYPE_OPTIONS = ["Joint Family", "Nuclear Family", "Others"];
export const FAMILY_STATUS_OPTIONS = ["Middle Class", "Upper Middle Class", "High class", "Rich/Affluent"];

export const FATHER_OCCUPATION_OPTIONS = [
  "- Select -",
  "Employed",
  "Business Man",
  "Professional",
  "Retired",
  "Not Employed",
  "Passed Away",
];

export const MOTHER_OCCUPATION_OPTIONS = [
  "- Select -",
  "Homemaker",
  "Employed",
  "Business Woman",
  "Professional",
  "Retired",
  "Passed Away",
];

export const SIBLINGS_COUNT_OPTIONS = [
  "- Select -",
  "none",
  "1",
  "2",
  "3",
  "4",
  "5",
  "5+",
];

export const PARTNER_RELIGION_OPTIONS = [
  "Any",
  "Hindu",
  "Muslim",
  "Christian",
  "Sikh",
  "Jain",
  "Buddhist",
  "Others",
];

export const PARTNER_MOTHER_TONGUE_OPTIONS = [
  "Any",
  "Telugu",
  "Tamil",
  "Hindi",
  "Kannada",
  "Malayalam",
  "English",
  "Bengali",
  "Marathi",
  "Gujarati",
  "Punjabi",
  "Odia",
  "Urdu",
  "Others",
];

export const PARTNER_EDUCATION_OPTIONS = [
  "Any",
  "10th",
  "12th",
  "Diploma",
  "Graduate",
  "B.Tech / B.E.",
  "M.Tech",
  "MBA",
  "Master's",
  "MBBS",
  "Doctorate",
  "Others",
];

export const PARTNER_COUNTRY_OPTIONS = [
  "Any",
  "India",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "United Arab Emirates",
  "Singapore",
  "Germany",
  "Others",
];

export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Telangana",
  "Karnataka",
  "Tamil Nadu",
  "Maharashtra",
  "Delhi",
  "Kerala",
  "Gujarat",
  "West Bengal",
  "Punjab",
  "Rajasthan",
  "Uttar Pradesh",
  "Others",
];

export const MAJOR_COUNTRIES = [
  "India",
  "United States",
  "United Kingdom",
  "United Arab Emirates",
  "Canada",
  "Australia",
  "Singapore",
  "Germany",
  "Others",
];

export const HOBBIES_CATEGORIES: Record<string, string[]> = {
  "Hobbies & Interests": [
    "Acting",
    "Art / Handicraft",
    "Bike / Car enthusiast",
    "Board games",
    "Clubbing",
    "Adventure sports",
    "Astrology",
    "Bird watching",
    "Book clubs",
    "Collectibles",
    "Blogging / Video blogging",
    "Calligraphy",
    "Cooking",
  ],
  Music: [
    "Classical",
    "Carnatic",
    "Hindustani",
    "Devotional",
    "Bollywood",
    "Telugu",
    "Instrumental",
    "Singing",
    "Playing instruments",
  ],
  Reading: [
    "Fiction",
    "Non-fiction",
    "Novels",
    "Poetry",
    "Spiritual",
    "Technology",
    "Biography",
    "Self-help",
  ],
  "Movie and TV shows": [
    "Movies",
    "Web series",
    "Drama",
    "Comedy",
    "Action",
    "Thriller",
    "Documentaries",
    "Telugu movies",
    "Bollywood",
  ],
  "Sports and Fitness": [
    "Cricket",
    "Football",
    "Badminton",
    "Tennis",
    "Gym",
    "Yoga",
    "Running",
    "Walking",
    "Swimming",
    "Adventure sports",
  ],
  Food: [
    "Vegetarian",
    "Non-Vegetarian",
    "Vegan",
    "Baking",
    "Cooking",
    "Dining out",
    "Food exploration",
  ],
  "Spoken languages": [
    "Telugu",
    "Hindi",
    "English",
    "Tamil",
    "Kannada",
    "Malayalam",
    "Marathi",
    "Gujarati",
    "Bengali",
    "Punjabi",
    "Urdu",
    "Odia",
    "Spanish",
    "French",
    "German",
  ],
};
