import { PrismaClient, Role, AccountStatus, VerificationStatus, ProfileStatus, PhotoStatus } from "@prisma/client";
import * as bcrypt from "bcryptjs";

const prisma = new PrismaClient();

interface DemoUserProfile {
  name: string;
  email: string;
  phone: string;
  gender: "FEMALE" | "MALE";
  dateOfBirth: Date;
  religion: string;
  caste: string;
  subCaste: string;
  gothram: string;
  motherTongue: string;
  height: number;
  weight: number;
  maritalStatus: string;
  education: string;
  occupation: string;
  income: number;
  city: string;
  state: string;
  country: string;
  bio: string;
  smoking: string;
  drinking: string;
  foodPreference: string;
  familyValues: string;
  familyDetails: string;
  horoscope: string;
  photoUrl: string;
  partnerPreference: {
    minAge: number;
    maxAge: number;
    minHeight: number;
    maxHeight: number;
    maritalStatus: string;
    religion: string;
    motherTongue: string;
    education: string;
    country: string;
  };
}

const demoProfiles: DemoUserProfile[] = [
  // ==========================================
  // 10 FEMALE PROFILES
  // ==========================================
  {
    name: "Ananya Sharma",
    email: "demo.female01@instantmatrimony.test",
    phone: "+91 98111 00101",
    gender: "FEMALE",
    dateOfBirth: new Date("1999-04-12"),
    religion: "Hindu",
    caste: "Brahmin",
    subCaste: "Saraswat",
    gothram: "Kashyapa",
    motherTongue: "Hindi",
    height: 165,
    weight: 55,
    maritalStatus: "NEVER_MARRIED",
    education: "MS in Computer Science (BITS Pilani)",
    occupation: "Senior Software Engineer (Microsoft)",
    income: 2400000,
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    bio: "Tech enthusiast and classical Kathak dancer. Passionate about AI innovation, weekend trekking, and reading contemporary literature.",
    smoking: "NO",
    drinking: "NO",
    foodPreference: "VEGETARIAN",
    familyValues: "LIBERAL",
    familyDetails: "Father is a retired banking officer, mother is a high school principal. One younger brother pursuing MBA.",
    horoscope: "Rashi: Mesha, Nakshatra: Ashwini",
    photoUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80",
    partnerPreference: {
      minAge: 27,
      maxAge: 32,
      minHeight: 172,
      maxHeight: 188,
      maritalStatus: "NEVER_MARRIED",
      religion: "Hindu",
      motherTongue: "Hindi",
      education: "Post Graduate / B.Tech / MS",
      country: "India",
    },
  },
  {
    name: "Pooja Reddy",
    email: "demo.female02@instantmatrimony.test",
    phone: "+91 98111 00102",
    gender: "FEMALE",
    dateOfBirth: new Date("1998-08-25"),
    religion: "Hindu",
    caste: "Reddy",
    subCaste: "Kapu Reddy",
    gothram: "Bharadwaja",
    motherTongue: "Telugu",
    height: 168,
    weight: 58,
    maritalStatus: "NEVER_MARRIED",
    education: "MBA in Marketing (ISB Hyderabad)",
    occupation: "Product Manager (Fintech Startup)",
    income: 2800000,
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    bio: "Energetic product leader who loves coffee, traveling to heritage destinations, and hosting family dinners.",
    smoking: "NO",
    drinking: "OCCASIONALLY",
    foodPreference: "NON_VEGETARIAN",
    familyValues: "MODERATE",
    familyDetails: "Father is an entrepreneur in real estate, mother is a homemaker. Elder sister is married and settled in USA.",
    horoscope: "Rashi: Vrishabha, Nakshatra: Rohini",
    photoUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&auto=format&fit=crop&q=80",
    partnerPreference: {
      minAge: 28,
      maxAge: 33,
      minHeight: 175,
      maxHeight: 190,
      maritalStatus: "NEVER_MARRIED",
      religion: "Hindu",
      motherTongue: "Telugu",
      education: "MBA / B.Tech / MS",
      country: "India",
    },
  },
  {
    name: "Dr. Sneha Nair",
    email: "demo.female03@instantmatrimony.test",
    phone: "+91 98111 00103",
    gender: "FEMALE",
    dateOfBirth: new Date("1996-11-03"),
    religion: "Hindu",
    caste: "Nair",
    subCaste: "Kiriyath",
    gothram: "Vasishta",
    motherTongue: "Malayalam",
    height: 162,
    weight: 54,
    maritalStatus: "NEVER_MARRIED",
    education: "MBBS, MD in Pediatrics (AIIMS)",
    occupation: "Consultant Pediatrician (Apollo Hospitals)",
    income: 2200000,
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    bio: "Dedicated doctor with a heart for community healthcare. Enjoys Carnatic music, yoga, and exploring south Indian cuisine.",
    smoking: "NO",
    drinking: "NO",
    foodPreference: "EGGETARIAN",
    familyValues: "TRADITIONAL",
    familyDetails: "Father is a retired civil surgeon, mother is a college professor. Only child.",
    horoscope: "Rashi: Tula, Nakshatra: Swati",
    photoUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&auto=format&fit=crop&q=80",
    partnerPreference: {
      minAge: 29,
      maxAge: 34,
      minHeight: 170,
      maxHeight: 185,
      maritalStatus: "NEVER_MARRIED",
      religion: "Hindu",
      motherTongue: "Malayalam",
      education: "MD / MS / MBBS / B.Tech",
      country: "India",
    },
  },
  {
    name: "Kavita Patel",
    email: "demo.female04@instantmatrimony.test",
    phone: "+91 98111 00104",
    gender: "FEMALE",
    dateOfBirth: new Date("2000-02-18"),
    religion: "Hindu",
    caste: "Patel",
    subCaste: "Leva Patel",
    gothram: "Sandilya",
    motherTongue: "Gujarati",
    height: 160,
    weight: 52,
    maritalStatus: "NEVER_MARRIED",
    education: "Chartered Accountant (CA - ICAI)",
    occupation: "Senior Financial Consultant (Ernst & Young)",
    income: 1900000,
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    bio: "CA professional with a balance of modern analytical mindset and deep cultural roots. Enjoys badminton and garba.",
    smoking: "NO",
    drinking: "NO",
    foodPreference: "VEGETARIAN",
    familyValues: "TRADITIONAL",
    familyDetails: "Traditional business family in Ahmedabad. Father runs textile exports, mother is a homemaker.",
    horoscope: "Rashi: Kumbha, Nakshatra: Shatabhisha",
    photoUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80",
    partnerPreference: {
      minAge: 26,
      maxAge: 30,
      minHeight: 168,
      maxHeight: 182,
      maritalStatus: "NEVER_MARRIED",
      religion: "Hindu",
      motherTongue: "Gujarati",
      education: "CA / MBA / Engineer / MS",
      country: "India",
    },
  },
  {
    name: "Meera Iyer",
    email: "demo.female05@instantmatrimony.test",
    phone: "+91 98111 00105",
    gender: "FEMALE",
    dateOfBirth: new Date("1997-09-14"),
    religion: "Hindu",
    caste: "Brahmin",
    subCaste: "Iyer",
    gothram: "Kaushika",
    motherTongue: "Tamil",
    height: 163,
    weight: 56,
    maritalStatus: "NEVER_MARRIED",
    education: "B.Tech (IIT Madras) + M.Des",
    occupation: "Lead UI/UX Product Designer",
    income: 2600000,
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    bio: "Design thinker with an eye for visual aesthetics and human-centered design. Veena player and amateur landscape photographer.",
    smoking: "NO",
    drinking: "NO",
    foodPreference: "VEGETARIAN",
    familyValues: "MODERATE",
    familyDetails: "Father is an executive director in PSU, mother is a classical music teacher. One elder brother settled in Germany.",
    horoscope: "Rashi: Kanya, Nakshatra: Hasta",
    photoUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=500&auto=format&fit=crop&q=80",
    partnerPreference: {
      minAge: 28,
      maxAge: 33,
      minHeight: 172,
      maxHeight: 186,
      maritalStatus: "NEVER_MARRIED",
      religion: "Hindu",
      motherTongue: "Tamil",
      education: "B.Tech / MS / M.Tech / MBA",
      country: "India",
    },
  },
  {
    name: "Rhea Deshmukh",
    email: "demo.female06@instantmatrimony.test",
    phone: "+91 98111 00106",
    gender: "FEMALE",
    dateOfBirth: new Date("1999-12-08"),
    religion: "Hindu",
    caste: "Maratha",
    subCaste: "96 Kuli Maratha",
    gothram: "Jamadagni",
    motherTongue: "Marathi",
    height: 167,
    weight: 59,
    maritalStatus: "NEVER_MARRIED",
    education: "Master of Laws (LL.M, ILS Pune)",
    occupation: "Corporate Legal Counsel",
    income: 2100000,
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    bio: "Corporate attorney specializing in IP law. Avid reader, pet lover, and amateur baker.",
    smoking: "NO",
    drinking: "OCCASIONALLY",
    foodPreference: "NON_VEGETARIAN",
    familyValues: "LIBERAL",
    familyDetails: "Father is a retired judge, mother is a social worker. One younger sister pursuing architecture.",
    horoscope: "Rashi: Dhanu, Nakshatra: Mula",
    photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&auto=format&fit=crop&q=80",
    partnerPreference: {
      minAge: 27,
      maxAge: 32,
      minHeight: 174,
      maxHeight: 188,
      maritalStatus: "NEVER_MARRIED",
      religion: "Hindu",
      motherTongue: "Marathi",
      education: "LLM / MBA / B.Tech / CA",
      country: "India",
    },
  },
  {
    name: "Simran Kaur",
    email: "demo.female07@instantmatrimony.test",
    phone: "+91 98111 00107",
    gender: "FEMALE",
    dateOfBirth: new Date("1998-05-20"),
    religion: "Sikh",
    caste: "Khatri",
    subCaste: "Arora",
    gothram: "N/A",
    motherTongue: "Punjabi",
    height: 170,
    weight: 60,
    maritalStatus: "NEVER_MARRIED",
    education: "M.Sc in Data Analytics",
    occupation: "Lead Data Scientist (E-commerce)",
    income: 2500000,
    city: "Chandigarh",
    state: "Punjab",
    country: "India",
    bio: "Tech professional grounded in Punjabi warmth and hospitality. Love road trips to Himachal and cooking authentic recipes.",
    smoking: "NO",
    drinking: "NO",
    foodPreference: "VEGETARIAN",
    familyValues: "TRADITIONAL",
    familyDetails: "Father is a government contractor, mother is a school coordinator. One brother in civil services.",
    horoscope: "Rashi: Simha, Nakshatra: Magha",
    photoUrl: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=500&auto=format&fit=crop&q=80",
    partnerPreference: {
      minAge: 28,
      maxAge: 33,
      minHeight: 178,
      maxHeight: 192,
      maritalStatus: "NEVER_MARRIED",
      religion: "Sikh",
      motherTongue: "Punjabi",
      education: "Post Graduate / B.Tech / MS",
      country: "India",
    },
  },
  {
    name: "Tanvi Kulkarni",
    email: "demo.female08@instantmatrimony.test",
    phone: "+91 98111 00108",
    gender: "FEMALE",
    dateOfBirth: new Date("1995-07-30"),
    religion: "Hindu",
    caste: "Brahmin",
    subCaste: "Deshastha",
    gothram: "Vishvamitra",
    motherTongue: "Marathi",
    height: 164,
    weight: 57,
    maritalStatus: "NEVER_MARRIED",
    education: "B.E. + Executive MBA (IIMB)",
    occupation: "Engineering Director (Cloud Infrastructure)",
    income: 3800000,
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    bio: "Tech executive who believes in continuous growth, mindful living, marathon running, and weekend art jamming.",
    smoking: "NO",
    drinking: "OCCASIONALLY",
    foodPreference: "EGGETARIAN",
    familyValues: "LIBERAL",
    familyDetails: "Well-educated nuclear family based in Bangalore. Parents are retired research scientists.",
    horoscope: "Rashi: Karka, Nakshatra: Pushya",
    photoUrl: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=500&auto=format&fit=crop&q=80",
    partnerPreference: {
      minAge: 30,
      maxAge: 36,
      minHeight: 172,
      maxHeight: 188,
      maritalStatus: "NEVER_MARRIED",
      religion: "Hindu",
      motherTongue: "Marathi",
      education: "MBA / B.Tech / MS",
      country: "India",
    },
  },
  {
    name: "Dr. Nidhi Agarwal",
    email: "demo.female09@instantmatrimony.test",
    phone: "+91 98111 00109",
    gender: "FEMALE",
    dateOfBirth: new Date("1997-03-15"),
    religion: "Hindu",
    caste: "Agarwal",
    subCaste: "Garg",
    gothram: "Garg",
    motherTongue: "Hindi",
    height: 158,
    weight: 51,
    maritalStatus: "NEVER_MARRIED",
    education: "BDS, MDS in Orthodontics",
    occupation: "Consultant Orthodontist",
    income: 2000000,
    city: "Jaipur",
    state: "Rajasthan",
    country: "India",
    bio: "Passionate dental specialist dedicated to creating confident smiles. Fond of Rajasthani folk art, heritage walks, and pottery.",
    smoking: "NO",
    drinking: "NO",
    foodPreference: "VEGETARIAN",
    familyValues: "TRADITIONAL",
    familyDetails: "Reputed business family in Jaipur with roots in manufacturing and hospitality.",
    horoscope: "Rashi: Mithuna, Nakshatra: Ardra",
    photoUrl: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=500&auto=format&fit=crop&q=80",
    partnerPreference: {
      minAge: 28,
      maxAge: 33,
      minHeight: 168,
      maxHeight: 182,
      maritalStatus: "NEVER_MARRIED",
      religion: "Hindu",
      motherTongue: "Hindi",
      education: "MDS / MBBS / CA / MBA / B.Tech",
      country: "India",
    },
  },
  {
    name: "Aishwarya Chowdhury",
    email: "demo.female10@instantmatrimony.test",
    phone: "+91 98111 00110",
    gender: "FEMALE",
    dateOfBirth: new Date("1998-10-10"),
    religion: "Hindu",
    caste: "Kayastha",
    subCaste: "Chowdhury",
    gothram: "Alambayana",
    motherTongue: "Bengali",
    height: 161,
    weight: 53,
    maritalStatus: "NEVER_MARRIED",
    education: "M.A. in Economics (Jadavpur University)",
    occupation: "Economic Research Analyst (Global Bank)",
    income: 1850000,
    city: "Kolkata",
    state: "West Bengal",
    country: "India",
    bio: "Economics researcher who loves Rabindrasangeet, poetry, theatre, and exploring old Calcutta cafes.",
    smoking: "NO",
    drinking: "NO",
    foodPreference: "NON_VEGETARIAN",
    familyValues: "MODERATE",
    familyDetails: "Father is an author and retired professor, mother is a curator. One elder brother in civil engineering.",
    horoscope: "Rashi: Tula, Nakshatra: Chitra",
    photoUrl: "https://images.unsplash.com/photo-1548142813-c348350df52b?w=500&auto=format&fit=crop&q=80",
    partnerPreference: {
      minAge: 28,
      maxAge: 33,
      minHeight: 170,
      maxHeight: 185,
      maritalStatus: "NEVER_MARRIED",
      religion: "Hindu",
      motherTongue: "Bengali",
      education: "Masters / Ph.D / B.Tech / MBA",
      country: "India",
    },
  },

  // ==========================================
  // 10 MALE PROFILES
  // ==========================================
  {
    name: "Aditya Varma",
    email: "demo.male01@instantmatrimony.test",
    phone: "+91 98222 00101",
    gender: "MALE",
    dateOfBirth: new Date("1996-06-14"),
    religion: "Hindu",
    caste: "Brahmin",
    subCaste: "Smartha",
    gothram: "Gautama",
    motherTongue: "Telugu",
    height: 178,
    weight: 74,
    maritalStatus: "NEVER_MARRIED",
    education: "B.Tech (IIT Bombay)",
    occupation: "Principal Staff Engineer (Google)",
    income: 4200000,
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    bio: "Software architect passionate about distributed systems, weekend tennis, sci-fi novels, and specialty pour-over coffee.",
    smoking: "NO",
    drinking: "OCCASIONALLY",
    foodPreference: "VEGETARIAN",
    familyValues: "MODERATE",
    familyDetails: "Father is a retired professor of physics, mother is a classical Sanskrit scholar. One younger sister working in finance.",
    horoscope: "Rashi: Mithuna, Nakshatra: Punarvasu",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80",
    partnerPreference: {
      minAge: 24,
      maxAge: 29,
      minHeight: 160,
      maxHeight: 172,
      maritalStatus: "NEVER_MARRIED",
      religion: "Hindu",
      motherTongue: "Telugu",
      education: "B.Tech / MS / MBA / CA",
      country: "India",
    },
  },
  {
    name: "Rohan Kapoor",
    email: "demo.male02@instantmatrimony.test",
    phone: "+91 98222 00102",
    gender: "MALE",
    dateOfBirth: new Date("1995-10-22"),
    religion: "Hindu",
    caste: "Khatri",
    subCaste: "Kapoor",
    gothram: "Vatsa",
    motherTongue: "Hindi",
    height: 182,
    weight: 78,
    maritalStatus: "NEVER_MARRIED",
    education: "MBA (FMS Delhi) + CFA Charterholder",
    occupation: "Vice President - Investment Banking",
    income: 4800000,
    city: "Delhi",
    state: "Delhi",
    country: "India",
    bio: "Finance professional with an energetic outlook on life. Enthusiast of historical documentaries, squash, and global travel.",
    smoking: "NO",
    drinking: "OCCASIONALLY",
    foodPreference: "NON_VEGETARIAN",
    familyValues: "LIBERAL",
    familyDetails: "Father is a senior advocate at Delhi High Court, mother is a psychologist. One younger brother.",
    horoscope: "Rashi: Tula, Nakshatra: Vishakha",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80",
    partnerPreference: {
      minAge: 25,
      maxAge: 30,
      minHeight: 162,
      maxHeight: 175,
      maritalStatus: "NEVER_MARRIED",
      religion: "Hindu",
      motherTongue: "Hindi",
      education: "MBA / CA / Post Graduate / B.Tech",
      country: "India",
    },
  },
  {
    name: "Dr. Siddharth Menon",
    email: "demo.male03@instantmatrimony.test",
    phone: "+91 98222 00103",
    gender: "MALE",
    dateOfBirth: new Date("1994-04-05"),
    religion: "Hindu",
    caste: "Nair",
    subCaste: "Swaroopathu",
    gothram: "Atri",
    motherTongue: "Malayalam",
    height: 175,
    weight: 71,
    maritalStatus: "NEVER_MARRIED",
    education: "MBBS, MS in Orthopedic Surgery",
    occupation: "Senior Orthopedic Surgeon",
    income: 3400000,
    city: "Kochi",
    state: "Kerala",
    country: "India",
    bio: "Dedicated surgeon who believes in empathy and work-life balance. Enjoys coastal cycling, classical guitar, and gardening.",
    smoking: "NO",
    drinking: "NO",
    foodPreference: "NON_VEGETARIAN",
    familyValues: "TRADITIONAL",
    familyDetails: "Well-respected family in Kerala. Father is a retired naval officer, mother is a teacher.",
    horoscope: "Rashi: Meena, Nakshatra: Uttara Bhadrapada",
    photoUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=500&auto=format&fit=crop&q=80",
    partnerPreference: {
      minAge: 26,
      maxAge: 31,
      minHeight: 160,
      maxHeight: 170,
      maritalStatus: "NEVER_MARRIED",
      religion: "Hindu",
      motherTongue: "Malayalam",
      education: "MBBS / MD / B.Tech / Masters",
      country: "India",
    },
  },
  {
    name: "Varun Reddy",
    email: "demo.male04@instantmatrimony.test",
    phone: "+91 98222 00104",
    gender: "MALE",
    dateOfBirth: new Date("1997-12-19"),
    religion: "Hindu",
    caste: "Reddy",
    subCaste: "Ganjam Reddy",
    gothram: "Kaundinya",
    motherTongue: "Telugu",
    height: 180,
    weight: 76,
    maritalStatus: "NEVER_MARRIED",
    education: "MS in Robotics (CMU, USA)",
    occupation: "Autonomous Systems Lead (Tech Hub)",
    income: 3900000,
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    bio: "Robotics engineer and robotics mentor. Love off-roading, astronomy stargazing, and home cooking.",
    smoking: "NO",
    drinking: "NO",
    foodPreference: "NON_VEGETARIAN",
    familyValues: "MODERATE",
    familyDetails: "Father owns a civil engineering firm, mother is an interior decorator. Younger sister married.",
    horoscope: "Rashi: Simha, Nakshatra: Purva Phalguni",
    photoUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80",
    partnerPreference: {
      minAge: 24,
      maxAge: 28,
      minHeight: 162,
      maxHeight: 174,
      maritalStatus: "NEVER_MARRIED",
      religion: "Hindu",
      motherTongue: "Telugu",
      education: "B.Tech / MS / MBA",
      country: "India",
    },
  },
  {
    name: "Kunal Patel",
    email: "demo.male05@instantmatrimony.test",
    phone: "+91 98222 00105",
    gender: "MALE",
    dateOfBirth: new Date("1996-03-28"),
    religion: "Hindu",
    caste: "Patel",
    subCaste: "Kadva Patel",
    gothram: "Parashara",
    motherTongue: "Gujarati",
    height: 176,
    weight: 73,
    maritalStatus: "NEVER_MARRIED",
    education: "B.E. (Chemical) + MS in Supply Chain",
    occupation: "Director of Operations (Pharma Exports)",
    income: 3500000,
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    bio: "Entrepreneurial leader managing international healthcare logistics. Enjoys cricket, Gujarati literature, and family festivals.",
    smoking: "NO",
    drinking: "NO",
    foodPreference: "VEGETARIAN",
    familyValues: "TRADITIONAL",
    familyDetails: "Established industrialist family in Gujarat with manufacturing plants across Vadodara and Ahmedabad.",
    horoscope: "Rashi: Vrishabha, Nakshatra: Mrigashirsha",
    photoUrl: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=500&auto=format&fit=crop&q=80",
    partnerPreference: {
      minAge: 24,
      maxAge: 29,
      minHeight: 158,
      maxHeight: 170,
      maritalStatus: "NEVER_MARRIED",
      religion: "Hindu",
      motherTongue: "Gujarati",
      education: "Graduate / CA / MBA / Engineer",
      country: "India",
    },
  },
  {
    name: "Vikramaditya Shinde",
    email: "demo.male06@instantmatrimony.test",
    phone: "+91 98222 00106",
    gender: "MALE",
    dateOfBirth: new Date("1995-08-11"),
    religion: "Hindu",
    caste: "Maratha",
    subCaste: "Deshmukh",
    gothram: "Bhrigu",
    motherTongue: "Marathi",
    height: 181,
    weight: 79,
    maritalStatus: "NEVER_MARRIED",
    education: "B.Tech (COEP) + MBA (IIM Lucknow)",
    occupation: "Management Consultant (Bain & Co)",
    income: 3600000,
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    bio: "Strategy consultant with a passion for problem solving, marathon training, photography, and jazz music.",
    smoking: "NO",
    drinking: "OCCASIONALLY",
    foodPreference: "EGGETARIAN",
    familyValues: "LIBERAL",
    familyDetails: "Father is an Indian Administrative Service officer (retired), mother is an educational trustee.",
    horoscope: "Rashi: Makara, Nakshatra: Shravana",
    photoUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=500&auto=format&fit=crop&q=80",
    partnerPreference: {
      minAge: 25,
      maxAge: 30,
      minHeight: 164,
      maxHeight: 176,
      maritalStatus: "NEVER_MARRIED",
      religion: "Hindu",
      motherTongue: "Marathi",
      education: "MBA / B.Tech / CA / Masters",
      country: "India",
    },
  },
  {
    name: "Jaspreet Singh",
    email: "demo.male07@instantmatrimony.test",
    phone: "+91 98222 00107",
    gender: "MALE",
    dateOfBirth: new Date("1997-05-09"),
    religion: "Sikh",
    caste: "Jat Sikh",
    subCaste: "Gill",
    gothram: "N/A",
    motherTongue: "Punjabi",
    height: 185,
    weight: 82,
    maritalStatus: "NEVER_MARRIED",
    education: "B.Tech in Civil Engineering",
    occupation: "Senior Project Manager (Infrastructure)",
    income: 2600000,
    city: "Chandigarh",
    state: "Punjab",
    country: "India",
    bio: "Passionate about building modern sustainable smart cities. Enthusiast of bhangra, agricultural innovation, and gym fitness.",
    smoking: "NO",
    drinking: "NO",
    foodPreference: "VEGETARIAN",
    familyValues: "TRADITIONAL",
    familyDetails: "Prominent family in Punjab. Father oversees agricultural estates, mother is a homemaker.",
    horoscope: "Rashi: Mesha, Nakshatra: Bharani",
    photoUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=500&auto=format&fit=crop&q=80",
    partnerPreference: {
      minAge: 24,
      maxAge: 28,
      minHeight: 165,
      maxHeight: 178,
      maritalStatus: "NEVER_MARRIED",
      religion: "Sikh",
      motherTongue: "Punjabi",
      education: "Graduate / Post Graduate / Engineer",
      country: "India",
    },
  },
  {
    name: "Karthik Sundaram",
    email: "demo.male08@instantmatrimony.test",
    phone: "+91 98222 00108",
    gender: "MALE",
    dateOfBirth: new Date("1996-11-27"),
    religion: "Hindu",
    caste: "Brahmin",
    subCaste: "Iyer",
    gothram: "Harita",
    motherTongue: "Tamil",
    height: 174,
    weight: 70,
    maritalStatus: "NEVER_MARRIED",
    education: "M.Tech in AI (IIT Delhi)",
    occupation: "Staff AI Research Scientist",
    income: 3800000,
    city: "Chennai",
    state: "Tamil Nadu",
    country: "India",
    bio: "AI researcher working on NLP and speech synthesis. Passionate about Carnatic violin, chess, and South Indian filter coffee.",
    smoking: "NO",
    drinking: "NO",
    foodPreference: "VEGETARIAN",
    familyValues: "TRADITIONAL",
    familyDetails: "Academic family based in Mylapore, Chennai. Father is a mathematics professor, mother is a bank manager.",
    horoscope: "Rashi: Vrishchika, Nakshatra: Anuradha",
    photoUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=500&auto=format&fit=crop&q=80",
    partnerPreference: {
      minAge: 24,
      maxAge: 29,
      minHeight: 160,
      maxHeight: 170,
      maritalStatus: "NEVER_MARRIED",
      religion: "Hindu",
      motherTongue: "Tamil",
      education: "B.Tech / M.Tech / MS / MBA",
      country: "India",
    },
  },
  {
    name: "Gaurav Agarwal",
    email: "demo.male09@instantmatrimony.test",
    phone: "+91 98222 00109",
    gender: "MALE",
    dateOfBirth: new Date("1994-09-02"),
    religion: "Hindu",
    caste: "Agarwal",
    subCaste: "Goyal",
    gothram: "Goyal",
    motherTongue: "Hindi",
    height: 177,
    weight: 75,
    maritalStatus: "NEVER_MARRIED",
    education: "Chartered Financial Analyst (CFA) + B.Com (SRCC)",
    occupation: "Senior Portfolio Manager",
    income: 3200000,
    city: "Jaipur",
    state: "Rajasthan",
    country: "India",
    bio: "Equity market enthusiast with high values for family traditions and honesty. Loves heritage architecture and swimming.",
    smoking: "NO",
    drinking: "NO",
    foodPreference: "VEGETARIAN",
    familyValues: "TRADITIONAL",
    familyDetails: "Respected Marwari business family in Jaipur. Father runs gemstone trading house.",
    horoscope: "Rashi: Kanya, Nakshatra: Uttara Phalguni",
    photoUrl: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=500&auto=format&fit=crop&q=80",
    partnerPreference: {
      minAge: 25,
      maxAge: 30,
      minHeight: 160,
      maxHeight: 172,
      maritalStatus: "NEVER_MARRIED",
      religion: "Hindu",
      motherTongue: "Hindi",
      education: "CA / MBA / Graduate",
      country: "India",
    },
  },
  {
    name: "Debanjan Sen",
    email: "demo.male10@instantmatrimony.test",
    phone: "+91 98222 00110",
    gender: "MALE",
    dateOfBirth: new Date("1996-01-20"),
    religion: "Hindu",
    caste: "Baidya",
    subCaste: "Sen",
    gothram: "Dhanvantari",
    motherTongue: "Bengali",
    height: 179,
    weight: 74,
    maritalStatus: "NEVER_MARRIED",
    education: "B.Tech (NIT Durgapur) + MS (USA)",
    occupation: "Senior Cloud Solutions Architect",
    income: 3300000,
    city: "Kolkata",
    state: "West Bengal",
    country: "India",
    bio: "Cloud architect with a love for indie films, acoustic guitar, football, and exploring diverse global cultures.",
    smoking: "NO",
    drinking: "OCCASIONALLY",
    foodPreference: "NON_VEGETARIAN",
    familyValues: "LIBERAL",
    familyDetails: "Culture-loving family in South Kolkata. Father is a consulting engineer, mother is a painter.",
    horoscope: "Rashi: Makara, Nakshatra: Dhanishta",
    photoUrl: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=500&auto=format&fit=crop&q=80",
    partnerPreference: {
      minAge: 24,
      maxAge: 29,
      minHeight: 160,
      maxHeight: 172,
      maritalStatus: "NEVER_MARRIED",
      religion: "Hindu",
      motherTongue: "Bengali",
      education: "B.Tech / Masters / MBA",
      country: "India",
    },
  },
];

async function seedDemoData() {
  console.log("==================================================");
  console.log("🚀 STARTING DEMO MATRIMONIAL DATA SEED");
  console.log("==================================================");
  console.log(`Total demo profiles to process: ${demoProfiles.length} (10 Female, 10 Male)\n`);

  const demoPassword = await bcrypt.hash("Demo@1234", 10);
  let createdCount = 0;
  let skippedCount = 0;
  let femaleCount = 0;
  let maleCount = 0;

  for (let i = 0; i < demoProfiles.length; i++) {
    const p = demoProfiles[i];
    const publicId = `IM8000${String(i + 1).padStart(4, "0")}`;

    // Idempotency check: look up user by unique email
    const existingUser = await prisma.user.findUnique({
      where: { email: p.email },
      include: { profile: true },
    });

    if (existingUser) {
      console.log(`[SKIP] Demo user already exists: ${p.email} (${existingUser.name})`);
      skippedCount++;
      if (p.gender === "FEMALE") femaleCount++;
      else maleCount++;
      continue;
    }

    console.log(`[CREATE] Seeding demo user: ${p.name} (${p.email} | ${p.gender})`);

    // 1. Create User
    const user = await prisma.user.create({
      data: {
        publicId,
        name: p.name,
        email: p.email,
        phone: p.phone,
        password: demoPassword,
        role: Role.USER,
        accountStatus: AccountStatus.ACTIVE,
        verificationStatus: VerificationStatus.VERIFIED,
        isActive: true,
        isEmailVerified: true,
        isPhoneVerified: true,
        emailVerified: new Date(),
      },
    });

    // 2. Create Profile
    const profile = await prisma.profile.create({
      data: {
        userId: user.id,
        gender: p.gender,
        dateOfBirth: p.dateOfBirth,
        religion: p.religion,
        caste: p.caste,
        subCaste: p.subCaste,
        gothram: p.gothram,
        motherTongue: p.motherTongue,
        height: p.height,
        weight: p.weight,
        maritalStatus: p.maritalStatus,
        education: p.education,
        occupation: p.occupation,
        income: p.income,
        city: p.city,
        state: p.state,
        country: p.country,
        bio: p.bio,
        smoking: p.smoking,
        drinking: p.drinking,
        foodPreference: p.foodPreference,
        familyValues: p.familyValues,
        familyDetails: p.familyDetails,
        horoscope: p.horoscope,
        completionPercent: 100,
        status: ProfileStatus.APPROVED,
      },
    });

    // 3. Create Partner Preferences
    await prisma.partnerPreference.create({
      data: {
        profileId: profile.id,
        minAge: p.partnerPreference.minAge,
        maxAge: p.partnerPreference.maxAge,
        minHeight: p.partnerPreference.minHeight,
        maxHeight: p.partnerPreference.maxHeight,
        maritalStatus: p.partnerPreference.maritalStatus,
        religion: p.partnerPreference.religion,
        motherTongue: p.partnerPreference.motherTongue,
        education: p.partnerPreference.education,
        country: p.partnerPreference.country,
      },
    });

    // 4. Create Main Approved Photo
    await prisma.photo.create({
      data: {
        profileId: profile.id,
        url: p.photoUrl,
        isMain: true,
        isApproved: true,
        status: PhotoStatus.APPROVED,
      },
    });

    createdCount++;
    if (p.gender === "FEMALE") femaleCount++;
    else maleCount++;
  }

  console.log("\n==================================================");
  console.log("🎉 DEMO MATRIMONIAL SEED COMPLETED SUCCESSFULLY");
  console.log("==================================================");
  console.log(`- Demo Users Created: ${createdCount}`);
  console.log(`- Existing Demo Users Preserved: ${skippedCount}`);
  console.log(`- Total Demo Accounts Active: ${createdCount + skippedCount}`);
  console.log(`  - Female Profiles: ${femaleCount}`);
  console.log(`  - Male Profiles: ${maleCount}`);
  console.log(`- Default Demo Login Password: Demo@1234\n`);
}

seedDemoData()
  .catch((e) => {
    console.error("❌ Error during demo data seed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
